# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Felipe Crestani
tagline:          'A Developer Blog - C#, .Net Core and MonoGame'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Felipe Crestani'
  url:            https://twitter.com/felipecrestani

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/tiolipexb
